TMDM-15085 Improper Neutralization of Directives in Dynamically Eval Code
Talend/tmdm-server-se pull request #1356
Opened 2021-06-15 04:24 UTC by htyin

https://jira.talendforge.org/browse/TMDM-15085?
**What is the current behavior?** (You should also link to an open issue here)

**What is the new behavior?**
Adding more restricted filter for userExpression.

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-06-15 05:34 UTC, pbabin requested changes

2021-06-15 05:34 UTC, pbabin commented on org.talend.mdm.core/src/com/amalto/core/util/Util.java
> +			userProperties.add("user_context.properites['']");
Typo here on 'properties'

2021-06-15 07:37 UTC, Gby56 requested changes
If possible, changing the current sanitizer to return known trusted data only.
Otherwise, the issue will come back in the scan, and after checking Veracode, we don't have annotations to "suppress" the issue in the code directly

2021-06-15 07:37 UTC, Gby56 commented on org.talend.mdm.core/src/com/amalto/core/util/Util.java
> +	private static boolean isUserContextProperty(String expression) {
Ideal solution would be to return the trusted hardcoded value instead of using the input expression, to break the untrusted data from flowing into the engine... Not sure how complex is the `user_context.properties['....']`

2021-06-15 07:44 UTC, htyin commented on org.talend.mdm.core/src/com/amalto/core/util/Util.java
> +	private static boolean isUserContextProperty(String expression) {
Properties are defined by user on web UI, can't be hardcoded.

2021-06-15 07:47 UTC, Gby56 commented on org.talend.mdm.core/src/com/amalto/core/util/Util.java
> +	private static boolean isUserContextProperty(String expression) {
Okay, so we'll manually mark the issue as fixed

2021-06-15 12:01 UTC, Gby56 approved these changes
Looks good to me !

2021-06-16 02:18 UTC, hw-zhu approved these changes

2021-06-18 05:31 UTC, merged